[package]
name = "amina_core_derive"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "amina_core_derive"
proc-macro = true

[dependencies]
syn = {version="1.0.105",features=["full","fold"]}
quote = "1.0.21"
darling = "0.14.2"
